// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package approvals.proxies;

public class Request extends system.proxies.WorkflowContext
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Approvals.Request";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		RequestID("RequestID"),
		Title("Title"),
		Description("Description"),
		Status("Status"),
		Requester("Approvals.Requester"),
		Approver("Approvals.Approver"),
		WorkflowInstance_WorkflowContext("System.WorkflowInstance_WorkflowContext");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Request(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Approvals.Request"));
	}

	protected Request(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject requestMendixObject)
	{
		super(context, requestMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Approvals.Request", requestMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Approvals.Request");
	}

	/**
	 * @deprecated Use 'Request.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static approvals.proxies.Request initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return approvals.proxies.Request.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static approvals.proxies.Request initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new approvals.proxies.Request(context, mendixObject);
	}

	public static approvals.proxies.Request load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return approvals.proxies.Request.initialize(context, mendixObject);
	}

	public static java.util.List<approvals.proxies.Request> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<approvals.proxies.Request> result = new java.util.ArrayList<approvals.proxies.Request>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Approvals.Request" + xpathConstraint))
			result.add(approvals.proxies.Request.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of RequestID
	 */
	public final java.lang.Long getRequestID()
	{
		return getRequestID(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestID
	 */
	public final java.lang.Long getRequestID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.RequestID.toString());
	}

	/**
	 * Set value of RequestID
	 * @param requestid
	 */
	public final void setRequestID(java.lang.Long requestid)
	{
		setRequestID(getContext(), requestid);
	}

	/**
	 * Set value of RequestID
	 * @param context
	 * @param requestid
	 */
	public final void setRequestID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long requestid)
	{
		getMendixObject().setValue(context, MemberNames.RequestID.toString(), requestid);
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final approvals.proxies.ENUM_Status getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final approvals.proxies.ENUM_Status getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null)
			return null;

		return approvals.proxies.ENUM_Status.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(approvals.proxies.ENUM_Status status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, approvals.proxies.ENUM_Status status)
	{
		if (status != null)
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
	}

	/**
	 * @return value of Requester
	 */
	public final mendixsso.proxies.MendixSSOUser getRequester() throws com.mendix.core.CoreException
	{
		return getRequester(getContext());
	}

	/**
	 * @param context
	 * @return value of Requester
	 */
	public final mendixsso.proxies.MendixSSOUser getRequester(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mendixsso.proxies.MendixSSOUser result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Requester.toString());
		if (identifier != null)
			result = mendixsso.proxies.MendixSSOUser.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Requester
	 * @param requester
	 */
	public final void setRequester(mendixsso.proxies.MendixSSOUser requester)
	{
		setRequester(getContext(), requester);
	}

	/**
	 * Set value of Requester
	 * @param context
	 * @param requester
	 */
	public final void setRequester(com.mendix.systemwideinterfaces.core.IContext context, mendixsso.proxies.MendixSSOUser requester)
	{
		if (requester == null)
			getMendixObject().setValue(context, MemberNames.Requester.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Requester.toString(), requester.getMendixObject().getId());
	}

	/**
	 * @return value of Approver
	 */
	public final mendixsso.proxies.MendixSSOUser getApprover() throws com.mendix.core.CoreException
	{
		return getApprover(getContext());
	}

	/**
	 * @param context
	 * @return value of Approver
	 */
	public final mendixsso.proxies.MendixSSOUser getApprover(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mendixsso.proxies.MendixSSOUser result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Approver.toString());
		if (identifier != null)
			result = mendixsso.proxies.MendixSSOUser.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Approver
	 * @param approver
	 */
	public final void setApprover(mendixsso.proxies.MendixSSOUser approver)
	{
		setApprover(getContext(), approver);
	}

	/**
	 * Set value of Approver
	 * @param context
	 * @param approver
	 */
	public final void setApprover(com.mendix.systemwideinterfaces.core.IContext context, mendixsso.proxies.MendixSSOUser approver)
	{
		if (approver == null)
			getMendixObject().setValue(context, MemberNames.Approver.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Approver.toString(), approver.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final approvals.proxies.Request that = (approvals.proxies.Request) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Approvals.Request";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
